#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Apply pruning threshold to precomputed layer contribution metrics."
    )
    parser.add_argument(
        "--metric-csv",
        required=True,
        help="Path to layer contribution CSV generated by compute_layer_contrib.py.",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.01,
        help="Prune threshold on normalized_contribution.",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output dir for prune artifacts. Default: metric CSV directory.",
    )
    args = parser.parse_args()

    metric_csv = Path(args.metric_csv).resolve()
    if not metric_csv.exists():
        raise FileNotFoundError(f"Metric CSV not found: {metric_csv}")

    out_dir = Path(args.output_dir).resolve() if args.output_dir else metric_csv.parent
    out_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(metric_csv)
    if "layer_idx" not in df.columns:
        raise ValueError("Metric CSV must contain column: layer_idx")

    if "normalized_contribution" not in df.columns:
        if "raw_contribution" not in df.columns:
            raise ValueError(
                "Metric CSV must contain normalized_contribution (or raw_contribution to derive it)."
            )
        raw_sum = float(df["raw_contribution"].sum())
        df["normalized_contribution"] = (
            df["raw_contribution"] / raw_sum if raw_sum > 0 else 0.0
        )

    df = df.sort_values("layer_idx").reset_index(drop=True)
    df["prune_candidate"] = df["normalized_contribution"] < float(args.threshold)

    prune_layers = df.loc[df["prune_candidate"], "layer_idx"].astype(int).tolist()
    keep_layers = df.loc[~df["prune_candidate"], "layer_idx"].astype(int).tolist()

    decisions_csv = out_dir / "layer_prune_decisions.csv"
    plan_json = out_dir / "prune_plan.json"
    df.to_csv(decisions_csv, index=False)

    plan = {
        "metric_csv": str(metric_csv),
        "threshold": float(args.threshold),
        "total_layers": int(len(df)),
        "prune_count": int(len(prune_layers)),
        "keep_count": int(len(keep_layers)),
        "prune_layers": prune_layers,
        "keep_layers": keep_layers,
        "artifacts": {
            "decisions_csv": str(decisions_csv),
            "prune_plan_json": str(plan_json),
        },
    }
    plan_json.write_text(json.dumps(plan, indent=2), encoding="utf-8")

    print(f"Metric CSV: {metric_csv}")
    print(f"Threshold: {args.threshold:.4f}")
    print(f"Prune layers: {len(prune_layers)}")
    print(f"Keep layers: {len(keep_layers)}")
    print(f"Wrote: {decisions_csv}")
    print(f"Wrote: {plan_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
